---
cloud_service_group: AppEngine
cloud_service_type: Version
name: Count By Environment
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.version.environment
        fields:
          - name: value
            operator: count
options:
  chart_type: PIE
  name_options:
    key: name
